### ISSUE TITLE
Add error msg to make up if certificates are missing. 

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/terraform-nomad-redash#14]
See https://github.com/fredrikhgrelland/vagrant-hashistack/blob/23757e884e266b5e1b2c799b9f8e5735ce931cb0/Makefile#L7-L8

**Comment by Neha-Sinha2305** [comment]
I went through the [Makefile](https://github.com/fredrikhgrelland/terraform-nomad-redash/blob/master/Makefile) and i see that we already have the error message regarding missing certificate added to the [update-box block](url). The user is presented with the link to [proxy section]( https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/README.md#if-you-are-behind-a-transparent-proxy) in the README file for the following commands:

1. ```make dev```
2.  ```make up ```
3.  ```make test ```,
Since, all the above have a dependency on 'update-box' so the user gets the error message as expected.

The only command that does not present the user with the link to the proxy section is :

1.  ```make template-example ``` as it does not depend on the  'update-box'

I am going ahead and adding the error message to the following line and i guess that should be good enough: https://github.com/fredrikhgrelland/terraform-nomad-redash/blob/c59576242e47ccaed98d083a073aa3eb50be8c6f/Makefile#L36

**Comment by Neha-Sinha2305** [comment]
This has been fixed in the PR: https://github.com/fredrikhgrelland/terraform-nomad-redash/pull/17 so can be closed.
